eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
logging:
  file: ./log/apiGatewayService.log
server:
  port: 8766
spring:
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true


