
server:
  port: 4444

cron:
  expression: "0 0 00 * * *"

logging:
  file: C:/elk/spring-boot-elk.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    ca.uhn.fhir.parser.LenientErrorHandler : ERROR


spring:
  data:
    mongodb:
      host: localhost #topoint to other pipelines change here
      port: 27017
      username: root
      password: root
      database: Registration

# Eureka integration config
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

integration:
  mirthBaseUrlRegistration: http://localhost:8072
  mirthBaseUrlEncouter: http://localhost:8073
  billingServiceID: sdgt-billing-service
  ruleEngineServiceID: rule-engine-service
  serviceMasterBaseUrl: http://localhost:8765/masters-service
  billingServiceBaseUrl: http://localhost:8765/sdgt-billing-service
  ruleEngineServiceBaseUrl: http://localhost:8765/rule-engine-service
  queueManagementServiceID : que-service
  auditTrailServiceID: audit-service
  schedulerServiceID: scheduler-service
  ipdServiceID: ipd-service
  isGLRequired: false
  apiKey: 47110664
  apiSecret: 65e07c7db685e4edcc2fbf06c12995be5bb3238b
  unitCode: PU
  orgCode: HUMS

  vedioConferenceRestrictMinute: 30
  sendMailBeforeAppointmentStartDate: 15
  beforeAppointmentMessage: Meeting is scheduled for future followed by appointment time.
  afterAppointmentMessage: Appointment scheduled for past.
  restrictUserMessage: Authorization restrict.
  medcareurl: medcare-prodiaqa.sdglobaltech.com
  prodiaServiceId: http://192.168.56.153:8080/ProdiaAPI/Web/serviceData/ws_in_out_post?
  appId: 31C0CBEA44

sms:
  smsUrlToPatient: http://localhost:8765/notification-service/notification/send?type=sms

registration-fee:
  active: true

kafka:
  bootstrapAddress: localhost:9092

filePath: /home/medcare/SDGT_Inventory/EmailAttachments/